anan.js text/javascript
console.log("anan")
console.log("anan")
console.log("anan")
console.log("anan")
console.log("anan")
console.log("anan")
console.log("anan")
console.log("anan")
console.log("anan")
console.log("anan")
